export const APIS_Endpoint = [
  {
    _id: 1,
    name: "Get All Products",
    Categories: "products",
    method: "get",
    url: "api/products",
    admin: false,
  },
  {
    _id: 2,
    name: "Get Specific Product",
    Categories: "products",
    method: "get",
    url: "api/products/:product_id",
    admin: false,
  },
  {
    _id: 3,
    name: "Create Product",
    Categories: "products",
    method: "post",
    url: "api/products",
    admin: true,
  },
  {
    _id: 4,
    name: "Update Product",
    Categories: "products",
    method: "put",
    url: "api/products/:product_id",
    admin: true,
  },
  {
    _id: 5,
    name: "Delete Product",
    Categories: "products",
    method: "delete",
    url: "api/products/:product_id",
    admin: true,
  },
  {
    _id: 6,
    name: "Get All Users",
    Categories: "users",
    method: "get",
    url: "api/users",
    admin: false,
  },
  {
    _id: 7,
    name: "Get Specific User",
    Categories: "users",
    method: "get",
    url: "api/users/:user_id",
    admin: false,
  },
  {
    _id: 8,
    name: "Create User",
    Categories: "users",
    method: "post",
    url: "api/users",
    admin: true,
  },
  {
    _id: 9,
    name: "Update User",
    Categories: "users",
    method: "put",
    url: "api/users/:user_id",
    admin: true,
  },
  {
    _id: 10,
    name: "Delete User",
    Categories: "users",
    method: "delete",
    url: "api/users/:user_id",
    admin: true,
  },
  {
    _id: 11,
    name: "Get All Orders",
    Categories: "orders",
    method: "get",
    url: "api/orders",
    admin: false,
  },
  {
    _id: 12,
    name: "Get Specific Order",
    Categories: "orders",
    method: "get",
    url: "api/orders/:order_id",
    admin: false,
  },
  {
    _id: 13,
    name: "Create Order",
    Categories: "orders",
    method: "post",
    url: "api/orders",
    admin: true,
  },
  {
    _id: 14,
    name: "Update Order",
    Categories: "orders",
    method: "put",
    url: "api/orders/:order_id",
    admin: true,
  },
  {
    _id: 15,
    name: "Delete Order",
    Categories: "orders",
    method: "delete",
    url: "api/orders/:order_id",
    admin: true,
  },
  {
    _id: 16,
    name: "Get All Order Items",
    Categories: "orders",
    method: "get",
    url: "api/order_items",
    admin: false,
  },
  {
    _id: 17,
    name: "Get Specific Order Item",
    Categories: "orders",
    method: "get",
    url: "api/order_items/:order_item_id",
    admin: false,
  },
  {
    _id: 18,
    name: "Create Order Item",
    Categories: "orders",
    method: "post",
    url: "api/order_items",
    admin: true,
  },
  {
    _id: 19,
    name: "Update Order Item",
    Categories: "orders",
    method: "put",
    url: "api/order_items/:order_item_id",
    admin: true,
  },
  {
    _id: 20,
    name: "Delete Order Item",
    Categories: "orders",
    method: "delete",
    url: "api/order_items/:order_item_id",
    admin: true,
  },
  {
    _id: 22,
    name: "Get Specific Categories",
    Categories: "Categories",
    method: "get",
    url: "api/name/:Categories_id",
    admin: false,
  },
  {
    _id: 23,
    name: "Create Categories",
    Categories: "Categories",
    method: "post",
    url: "api/name",
    admin: true,
  },
  {
    _id: 24,
    name: "Update Categories",
    Categories: "Categories",
    method: "put",
    url: "api/name/:Categories_id",
    admin: true,
  },
  {
    _id: 25,
    name: "Delete Categories",
    Categories: "Categories",
    method: "delete",
    url: "api/name/:Categories_id",
    admin: true,
  },
  {
    _id: 26,
    name: "Get All Carts",
    Categories: "Carts",
    method: "get",
    url: "api/carts",
    admin: false,
  },
  {
    _id: 27,
    name: "Get Specific Cart",
    Categories: "Carts",
    method: "get",
    url: "api/carts/:cart_id",
    admin: false,
  },
  {
    _id: 28,
    name: "Create Cart",
    Categories: "Carts",
    method: "post",
    url: "api/carts",
    admin: true,
  },
  {
    _id: 29,
    name: "Update Cart",
    Categories: "Carts",
    method: "put",
    url: "api/carts/:cart_id",
    admin: true,
  },
  {
    _id: 30,
    name: "Delete Cart",
    Categories: "Carts",
    method: "delete",
    url: "api/carts/:cart_id",
    admin: true,
  },
  {
    _id: 31,
    name: "Get All Billboards",
    Categories: "Billboards",
    method: "get",
    url: "api/billboards",
    admin: false,
  },
  {
    _id: 32,
    name: "Get Specific Billboard",
    Categories: "Billboards",
    method: "get",
    url: "api/billboards/:billboard_id",
    admin: false,
  },
  {
    _id: 33,
    name: "Create Billboard",
    Categories: "Billboards",
    method: "post",
    url: "api/billboards",
    admin: true,
  },
  {
    _id: 34,
    name: "Update Billboard",
    Categories: "Billboards",
    method: "put",
    url: "api/billboards/:billboard_id",
    admin: true,
  },
  {
    _id: 35,
    name: "Delete Billboard",
    Categories: "Billboards",
    method: "delete",
    url: "api/billboards/:billboard_id",
    admin: true,
  },
  {
    _id: 36,
    name: "Get All Sizes",
    Categories: "Sizes",
    method: "get",
    url: "api/sizes",
    admin: false,
  },
  {
    _id: 37,
    name: "Get Specific Size",
    Categories: "Sizes",
    method: "get",
    url: "api/sizes/:size_id",
    admin: false,
  },
  {
    _id: 38,
    name: "Create Size",
    Categories: "Sizes",
    method: "post",
    url: "api/sizes",
    admin: true,
  },
  {
    _id: 39,
    name: "Update Size",
    Categories: "Sizes",
    method: "put",
    url: "api/sizes/:size_id",
    admin: true,
  },
  {
    _id: 40,
    name: "Delete Size",
    Categories: "Sizes",
    method: "delete",
    url: "api/sizes/:size_id",
    admin: true,
  },
  {
    _id: 41,
    name: "Get All Colors",
    Categories: "Colors",
    method: "get",
    url: "api/colors",
    admin: false,
  },
  {
    _id: 42,
    name: "Get Specific Color",
    Categories: "Colors",
    method: "get",
    url: "api/colors/:color_id",
    admin: false,
  },
  {
    _id: 43,
    name: "Create Color",
    Categories: "Colors",
    method: "post",
    url: "api/colors",
    admin: true,
  },
  {
    _id: 44,
    name: "Update Color",
    Categories: "Colors",
    method: "put",
    url: "api/colors/:color_id",
    admin: true,
  },
  {
    _id: 45,
    name: "Delete Color",
    Categories: "Colors",
    method: "delete",
    url: "api/colors/:color_id",
    admin: true,
  },
];
